spring :  

   #数据库配置
  datasource : 
    url : jdbc:mysql://192.168.1.253:3306/UserLogin
    username : root
    password : pass
    driver-class-name : com.mysql.jdbc.Driver
    max-idle : 10
    min-idle : 5 
    initial-size : 5
    validation-query : SELECT  1
    test-on-borrow : false 
    test-while-idle : true
    time-between-eviction-runs-millis : 18800
    jdbc-interceptors : ConnectionState;SlowQueryReport(threshold=0)
    
mybatis: 
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage : com.ocs.ms.entity 
server : 
  port : 8088
redis :
  host : 192.168.1.253
  port : 6379